name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Test Parameters
      id: params
      run: |
        echo ::set-output name=namespace::kubedb-enterprise-$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')

    - name: Print
      run: |
        echo ">>>>>" ${{ steps.params.outputs.namespace }}
